Feature/ys dev add container params
radiome-lab/cpac pull request #1
Opened 2021-04-08 14:03 UTC by YiranCdr

2021-04-13 15:54 UTC, anibalsolon requested changes
The static solution to store the key is fine. However, your auth key solution does not prevent someone to access the other endpoints, nor the websocket.

The pipeline parameters looks good, just small logic changes.

2021-04-13 15:54 UTC, anibalsolon commented on src/cpac/api/authKey.py
> +    def generateKey():
In Python, method names are snake-case: generate_key

2021-04-13 15:54 UTC, anibalsolon commented on src/cpac/api/authKey.py
> +    def getKey():
snake-case

2021-04-13 15:54 UTC, anibalsolon commented on src/cpac/api/backends/container.py
> +                if 'parallelPipeline' in self.execution_params else []
Let's invert this logic for these three conditionals, like this:

```python
if 'parallelPipeline' in self.execution_params:
    parallel_pipelines = int(self.execution_params['parallelPipeline'])
    command += ['--pipeline_override', f'maximumMemoryPerParticipant: {parallel_pipelines}']
```

and it is not `maximumMemoryPerParticipant`, but `numParticipantsAtOnce`

2021-04-13 15:54 UTC, anibalsolon commented on src/cpac/api/server.py
> +        ifWrongAuthKey = False
Please use snake case variables on Python

2021-04-13 15:54 UTC, anibalsolon commented on src/cpac/api/server.py
> +        ifWrongAuthKey = False
and 

```python
wrong_key = 'authKey' not in self.json or self.json['authKey'].strip() != AuthKey.getKey()
```

2021-05-22 05:05 UTC, YiranCdr commented on src/cpac/api/authKey.py
> +    def generateKey():
Fixed.

2021-05-22 05:05 UTC, merged